### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by TheEnjinia** [1s0n/Mangareader-Downloader-v2#1]
Trying to get me the earlier One Piece Chapters in japanese and doesn't work so far.
First thing is, that it's missing a temp folder, which I added manually. After that it still crashes:

URL: https://mangareader.to/read/one-piece-colored-edition-55493/ja/volume-1

DevTools listening on ws://127.0.0.1:61160/devtools/browser/ed97e837-5229-4f46-b14d-c3e76f9171ef
[0425/115414.190:INFO:CONSOLE(1)] "JQMIGRATE: Migrate is installed, version 3.3.2", source: https://mangareader.to/js/app.min.js?v=2.1 (1)
[0425/115414.530:INFO:CONSOLE(7)] "Version: 1.0.0 - Time: 12:17:08, 21/4/2023 API", source: https://services.vlitag.com/adv1/?q=591701d038949ac7ff56b261301cad42 (7)
[0425/115414.917:INFO:CONSOLE(447)] "The function registerDeletion is not defined", source: https://assets.vlitag.com/plugins/cmptcf2/cmp-v2.0.1.js (447)
[0425/115414.923:INFO:CONSOLE(447)] "The function registerDeletion is not defined", source: https://assets.vlitag.com/plugins/cmptcf2/cmp-v2.0.1.js (447)
[0425/115414.966:INFO:CONSOLE(447)] "The function registerDeletion is not defined", source: https://assets.vlitag.com/plugins/cmptcf2/cmp-v2.0.1.js (447)
[0425/115415.645:INFO:CONSOLE(0)] "Fetch event handler is recognized as no-op. No-op fetch handler may bring overhead during navigation. Consider removing the handler if possible.", source:  (0)
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    horizon_button.click()
  File "C:\Users\dummy\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\dummy\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 404, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\dummy\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dummy\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="javascript:;" class="rtl-row mode-item" data-value="horizontal">...</a> is not clickable at point (400, 375). Other element would receive the click: <div style="position: absolute; top: 0px; left: 0px; width: 800px; height: 600px; z-index: 2147483647; pointer-events: auto;"></div>
  (Session info: headless chrome=112.0.5615.86)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00895E23+53059]
        (No symbol) [0x00824AF1]
        (No symbol) [0x0071B388]
        (No symbol) [0x007541D8]
        (No symbol) [0x00751CA4]
        (No symbol) [0x0074F3AB]
        (No symbol) [0x0074DC58]
        (No symbol) [0x00742DE7]
        (No symbol) [0x0076A7CC]
        (No symbol) [0x00742746]
        (No symbol) [0x0076AB24]
        (No symbol) [0x0078066F]
        (No symbol) [0x0076A5C6]
        (No symbol) [0x00740A2C]
        (No symbol) [0x007420ED]
        GetHandleVerifier [0x00AFD3CE+2573550]
        GetHandleVerifier [0x00B33340+2794592]
        GetHandleVerifier [0x00B2CF1C+2768956]
        GetHandleVerifier [0x0092FA60+682880]
        (No symbol) [0x0082EE22]
        (No symbol) [0x0082A8B8]
        (No symbol) [0x0082A99B]
        (No symbol) [0x0081DB57]
        BaseThreadInitThunk [0x76AF00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77537BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77537B8E+238]

**Comment by 1s0n** [comment]
Yes it still works, I didn't expect anyone to use it and didn't push through updates and specific instructions on how to use it. Ill push the updates now.

Also that is caused by the clicks getting intercepted by ads, I still miss the days when mangareader and zoro were both adfree lol.

**Comment by 1s0n** [comment]
It should work now.
(Open another issue if it doesn't ig soz)
