### ISSUE TITLE
The Main.py,  and batch.py files don't Start Downloading.  

### ISSUE THREAD

**Issue by UnionAdmin2286** [1s0n/Mangareader-Downloader-v2#19]
in main.py,  you enter the URL,   And it simply does nothing.   the URL shows up as entered.  and then after like 10 minutes you get an error

"WARNING:selenium.webdriver.common.selenium_manager:The chromedriver version (124.0.6367.91) detected in PATH at D:\Media Archive\Mangareader-Downloader-v2-master\Mangareader-Downloader-v2-master\chromedriver.exe might not be compatible with the detected chrome version (126.0.6478.126); currently, chromedriver 126.0.6478.126 is recommended for chrome 126.*, so it is advised to delete the driver in PATH and retry

DevTools listening on ws://127.0.0.1:63415/devtools/browser/7609657c-9968-4c72-aac2-e48d2d041780
Traceback (most recent call last):
  File "D:\Media Archive\Mangareader-Downloader-v2-master\Mangareader-Downloader-v2-master\main.py", line 129, in <module>
    download_volume(url)
  File "D:\Media Archive\Mangareader-Downloader-v2-master\Mangareader-Downloader-v2-master\main.py", line 44, in download_volume
    driver = webdriver.Chrome(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 124
Current browser version is 126.0.6478.126 with binary path C:\Users\james\.cache\selenium\chrome\win64\126.0.6478.126\chrome.exe
Stacktrace:
        GetHandleVerifier [0x00EFC113+48259]
        (No symbol) [0x00E8CA41]
        (No symbol) [0x00D80A17]
        (No symbol) [0x00DB2BFA]
        (No symbol) [0x00DB1FFB]
        (No symbol) [0x00DAD67F]
        (No symbol) [0x00DA9239]
        (No symbol) [0x00DEA8BA]
        (No symbol) [0x00DEA0EA]
        (No symbol) [0x00DE0B36]
        (No symbol) [0x00DB570D]
        (No symbol) [0x00DB62CD]
        GetHandleVerifier [0x011B6533+2908323]
        GetHandleVerifier [0x011F3B4B+3159739]
        GetHandleVerifier [0x00F9505B+674763]
        GetHandleVerifier [0x00F9B21C+699788]
        (No symbol) [0x00E96244]
        (No symbol) [0x00E92298]
        (No symbol) [0x00E9242C]
        (No symbol) [0x00E84BB0]
        BaseThreadInitThunk [0x75BF7BA9+25]
        RtlInitializeExceptionChain [0x7718C10B+107]
        RtlClearBits [0x7718C08F+191]

"

i'm pretty sure this is a problem with my chromedriver version so i'll update it and get back to this

**Comment by 1s0n** [comment]
Yea it is, should be fine after you update
