### ISSUE TITLE
Doesn't work now

### ISSUE THREAD

**Issue by Durubhuru14** [1s0n/Mangareader-Downloader-v2#24]
`  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Durvesh\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\Durvesh\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Durvesh\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 126, in <module>
        File "<string>", line 105, in uses_msvc
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
          self._compile(body, headers, include_dirs, lang)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 379, in compile
          self.initialize()
          ~~~~~~~~~~~~~~~^^
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 289, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\Durvesh\AppData\Local\Temp\pip-build-env-ojs6nzgx\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 150, in _get_vc_env
          raise DistutilsPlatformError(
          ...<3 lines>...
          )
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

This happens when `pip3 install -r requirements.txt` is executed.
Even i tried to install everything manually still doesn't work.

**Comment by 1s0n** [comment]
if you open your eyes and read the error carefully, the solution is in the error ![image](https://github.com/user-attachments/assets/75cf2b2d-d034-448a-89f9-236d7e2df915)
also this isn't even a problem with my code ik it has problems but this ain't one of them so stop commenting on peoples posts

**Comment by Durubhuru14** [comment]
mb
